						</div>
						<!-- Main msg box (end) -->
					</div>
		    		<!-- Main msg (end) -->
		    	</div>
		    	<!-- Content (end) -->
		    </div>
		    <!-- Site Content (end) -->

		    <!-- Footer (begin) -->
		    <footer>
				www.SabongNow.com&nbsp;<a href=""><img src="img/fb.png" width="25" height="25" ></a>
				&nbsp;<a href=""><img src="img/TwitterIcon.png" width="25" height="25" ></a>&nbsp;<a href=""><img src="img/download.png" width="25" height="25" ></a>
		    </footer>
		    <p>&nbsp;</p>		    
		    <!-- Footer (end) -->
		</div>
		<!-- Main Container (end) -->
	</body>
</html>

<?php 
if (isset($_SESSION['errormessage']))
{
	$_SESSION['errormessage'] = ""; 
}

if (isset($_SESSION['registermessage']))
{
	$_SESSION['registermessage'] = ""; 
}
?>
